---
title: 3D-hanger
hero_image: images/banner.png
description: Ontwerp een hanger om 3D te printen en te dragen.
version: 4
duration: 2 #possible values: 1, 2 or 3
theme: green
listed: true
copyedit: true
last_tested: "2018-03-21"
site_areas:
steps:
  - 
    title: Inleiding
  - 
    title: Maak een ring
  - 
    title: Voeg meer ringen toe
  - 
    title: Voeg een rand toe
  - 
    title: Voeg een bevestigingsring toe
  - 
    title: "Uitdaging: verander de hanger"
  - 
    title: 3D print en monteer je hanger
