title: 3D printable pendant
hero_image: images/banner.png
description: blockscad-pendant description
version: 4
duration: 2 # possible values: 1, 2 or 3
theme: green
listed: false
copyedit: false
last_tested: "2018-03-21"
site_areas:
steps:
  - title: Introduction
  - title: Create a hoop
  - title: Add more hoops
  - title: Add a border
  - title: Add a hanging hoop
  - title: "Challenge: Change the pendant!"
  - title: 3D print and assemble your pendant
