---
title: 3D pendant
hero_image: images/banner.png
description: Design a pendant to 3D print and wear.
version: 4
duration: 2
theme: green
listed: true
copyedit: true
last_tested: '2018-03-21'
site_areas: 
steps:
- title: Introduction
- title: Create a hoop
  completion:
  - engaged
- title: Add more hoops
- title: Add a border
- title: Add a hanging hoop
- title: 'Challenge: Change the pendant'
  completion:
  - internal
- title: 3D print and assemble your pendant
  completion:
  - external
