## Create a hoop

The design uses 6 interlocking hoops in the centre and a larger hoop around the outside. The pendant is 4cm wide, plus the hoop for hanging. It is 2mm deep, so it will 3D print quite quickly.

First, make a single inner hoop. 

--- task ---
Open the BlocksCAD editor in a web browser [blockscad3d.com/editor/](https://www.blockscad3d.com/editor/){:target="_blank"}.

You can drag and drop blocks to write code to create 3D objects. 

--- /task ---
--- task ---
Create a cylinder with a radius of 12mm and a height of 2mm. 

![screenshot](images/pendant-cylinder.png) 
	
Cylinders are automatically centred along the X and Y axes. Select 'not centered' so that the pendant will sit on the 'surface'.
	
Click on the `Render` button after each change to your code to see the results. 

--- /task ---
--- task ---
Now use `difference`{:class="blockscadsetops"} to remove a smaller cylinder from the centre. This will create a hoop:

![screenshot](images/pendant-hoop.png) 
	
If you like, you can click on the coloured square to change the colour used in the viewer. This will not affect the colour of your pendant, as that will depend on the colour of the filament that you use. 
	
--- /task ---
	
	
