---
title: 3D झुमका
hero_image: images/banner.png
description: एक 3D झुमके का डिजाइन बनाइए और उसे प्रिंट करके पहने।
version: 4
duration: 2 #possible values: 1, 2 or 3
theme: green
listed: true
copyedit: true
last_tested: "2018-03-21"
site_areas:
steps:
  - title: परिचय
  - title: एक घेरा बनाएँ
  - title: अधिक घेरा जोड़ें
  - title: एक सीमा जोड़ें
  - title: एक लटका हुआ घेरा जोड़ें
  - title: "चुनौती: झुमके को बदलें"
  - title: अपने झुमके को 3D प्रिंट करें और जोड़ें
