---
title: 3D pendant
hero_image: images/banner.png
description: Design a pendant to 3D print and wear.
version: 4
duration: 2 #possible values: 1, 2 or 3
theme: green
listed: true
copyedit: true
last_tested: "2018-03-21"
site_areas:
steps:
  - 
    title: परिचय
  - 
    title: एक घेरा बनाएँ
  - 
    title: अधिक घेरा जोड़ें
  - 
    title: एक सीमा जोड़ें
  - 
    title: एक लटका हुआ घेरा जोड़ें
  - 
    title: "Challenge: Change the pendant"
  - 
    title: 3D print and assemble your pendant
