---
title: Colgante 3D
hero_image: images/banner.png
description: Diseña un colgante para imprimir en 3D y llevarlo puesto.
version: 4
duration: 2
theme: green
listed: true
copyedit: true
last_tested: '2018-03-21'
site_areas: 
steps:
- title: Introducción
- title: Crea un aro
- title: Añade más aros
  completion:
  - engaged
- title: Agrega un borde
- title: Agrega un aro para colgar
- title: 'Desafío: Cambia el colgante'
- title: Imprime en 3D y monta tu colgante
  completion:
  - internal
