---
title: 3D-Anhänger
hero_image: images/banner.png
description: Gestalte einen Anhänger zum 3D-Drucken und tragen.
version: 4
duration: 2 #possible values: 1, 2 or 3
theme: green
listed: true
copyedit: true
last_tested: "2018-03-21"
site_areas:
steps:
  - 
    title: Einleitung
  - 
    title: Einen Reifen erstellen
  - 
    title: Füge mehr Reifen hinzu
  - 
    title: Füge einen Rand hinzu
  - 
    title: Füge einen Aufhänge-Reifen hinzu
  - 
    title: "Herausforderung: Ändere den Anhänger"
  - 
    title: 3D-Drucke deinen Anhänger und baue ihn zusammen
