---
title: Pingente 3D
hero_image: images/banner.png
description: Crie um pingente para imprimir em 3D e usar.
version: 4
duration: 2
theme: green
listed: true
copyedit: true
last_tested: '2018-03-21'
site_areas:
steps:
  - 
    title: Introdução
  - 
    title: Crie uma argola
  - 
    title: Adicione mais argolas
    completion:
      - engaged
  - 
    title: Adicione uma borda
  - 
    title: Adicione uma argola para pendurar
  - 
    title: 'Desafio: Mude o pingente'
  - 
    title: Imprima em 3D e monte o seu pingente
    completion:
      - internal
