---
title: قلادة ثلاثية الابعاد
hero_image: images/banner.png
description: تصميم قلادة ثلاثية الأبعاد وأرتدائها.
version: 4
duration: 2
theme: green
listed: true
copyedit: true
last_tested: '2018-03-21'
site_areas:
steps:
- title: المقدمة
  completion: engaged
- title: إنشئ طوق
- title: أضف المزيد من الأطواق
- title: أضف حدًا
- title: أضف طوقا معلق
- title: 'التحدي: قم بتغيير القلادة'
  completion: internal
- title: طباعة ثلاثية الأبعاد وتجميع القلادة الخاصة بك
