---
title: 3D μενταγιόν
hero_image: images/banner.png
description: Σχεδίασε ένα μενταγιόν για 3D εκτυπωτή και φόρεσέ το.
version: 4
duration: 2
theme: green
listed: true
copyedit: true
last_tested: '2018-03-21'
site_areas: 
steps:
- title: Εισαγωγή
- title: Δημιούργησε έναν  στεφάνη
- title: Πρόσθεσε περισσότερα κρίκους
  completion:
  - engaged
- title: Βάλε περίγραμμα
- title: Πρόσθεσε έναν στεφάνι για κρέμασμα
- title: 'Πρόκληση: Άλλαξε το μενταγιόν'
- title: 3D εκτύπωση και συναρμολόγηση του μενταγιόν
  completion:
  - internal
