---
title: Pendentif 3D
hero_image: images/banner.png
description: Conçois un pendentif à imprimer en 3D et à porter.
version: 4
duration: 2
theme: green
listed: true
copyedit: true
last_tested: '2018-03-21'
site_areas:
steps:
  - 
    title: Introduction
  - 
    title: Créer un cerceau
  - 
    title: Ajouter plus de cerceaux
    completion:
      - engaged
  - 
    title: Ajouter une bordure
  - 
    title: Ajouter une attache
  - 
    title: 'Défi : changer le pendentif'
  - 
    title: Impression 3D et montage de ton pendentif
    completion:
      - internal
